# Generated by Django 5.2.8 on 2025-11-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('stem', 'STEM'), ('arts', 'Arts & Humanities'), ('business', 'Business & Commerce'), ('health', 'Health Sciences'), ('education', 'Education'), ('technical', 'Technical & Vocational')], max_length=100)),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_outlook', models.CharField(choices=[('high', 'High Demand'), ('medium', 'Medium Demand'), ('low', 'Low Demand')], max_length=50)),
                ('kenyan_market_demand', models.CharField(choices=[('growing', 'Growing'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('sciences', 'Sciences'), ('humanities', 'Humanities'), ('languages', 'Languages'), ('technical', 'Technical'), ('business', 'Business')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CareerPersonalityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reasoning', models.TextField()),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.career')),
                ('personality_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.personalitytype')),
            ],
        ),
        migrations.AddField(
            model_name='career',
            name='personality_types',
            field=models.ManyToManyField(through='recommendations.CareerPersonalityMatch', to='assessments.personalitytype'),
        ),
        migrations.CreateModel(
            name='LearningStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic')], max_length=50)),
                ('description', models.TextField()),
                ('study_recommendations', models.TextField()),
                ('personality_types', models.ManyToManyField(to='assessments.personalitytype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_match_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('academic_match_score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.career')),
            ],
        ),
    ]
