# Generated by Django 5.2.8 on 2025-11-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentrecommendation',
            name='recommended_subjects',
            field=models.ManyToManyField(to='recommendations.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='recommended_subjects',
            field=models.ManyToManyField(related_name='careers_recommending', to='recommendations.subject'),
        ),
        migrations.AddField(
            model_name='career',
            name='required_subjects',
            field=models.ManyToManyField(related_name='careers_requiring', to='recommendations.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='careerpersonalitymatch',
            unique_together={('career', 'personality_type')},
        ),
        migrations.AlterUniqueTogether(
            name='studentrecommendation',
            unique_together={('student', 'career')},
        ),
    ]
