# Generated by Django 5.2.8 on 2025-11-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='personality_types',
        ),
        migrations.RemoveField(
            model_name='learningstyle',
            name='personality_types',
        ),
    ]
