# Generated by Django 5.2.8 on 2025-11-19 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('recommendations', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.JSONField(default=dict)),
                ('challenges', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.learningstyle')),
                ('personality_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.personalitytype')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_from_ai', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_coach.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ResourceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('course', 'Online Course'), ('tool', 'Tool/Software')], max_length=50)),
                ('relevance_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('coaching_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ai_coach.coachingplan')),
            ],
        ),
    ]
